// This object may become quite large, so there may be a tangible benefit to
// parsing a JSON string.
const EXERCISES = JSON.parse(`
  {
    "doggo-ipsum": {
      "name": "Doggo Ipsum",
      "content": "Doggo ipsum much ruin diet sub woofer big ol long doggo, doggo puggorino clouds, length boy much ruin diet. shibe shooberino. Doge you are doin me a concern tungg heckin good boys and girls many pats smol, ur givin me a spook porgo borking doggo shoob, noodle horse dat tungg tho sub woofer big ol pupper. Vvv shooberino borkdrive, such treat. Dat tungg tho heckin good boys extremely cuuuuuute shoob puggo, shibe most angery pupper I have ever seen. Noodle horse fluffer noodle horse stop it fren shoob puggorino, woofer length boy floofs heckin. Shibe most angery pupper I have ever seen doggorino pupperino, heck. you are doing me a frighten. Noodle horse very hand that feed shibe very jealous pupper puggorino, blop. Porgo heckin angery woofer doge fat boi long doggo borkdrive, bork borkf much ruin diet. Borking doggo doggorino shoober thicc borkdrive boof much ruin diet, tungg h*ck pupperino many pats floofs. Heckin good boys borkf smol borkf super chub, sub woofer adorable doggo. tungg blop pats. Adorable doggo long water shoob corgo dat tungg tho stop it fren lotsa pats shooberino, big ol heckin good boys and girls heck fat boi most angery pupper I have ever seen. Borkf boof what a nice floof blop wrinkler borking doggo dat tungg tho, borkf boof borkdrive super chub. Mlem aqua doggo very taste wow blep, lotsa pats. Pats heck wrinkler very jealous pupper you are doin me a concern most angery pupper I have ever seen vvv wrinkler noodle horse, lotsa pats boof shoober the neighborhood pupper wow very biscit boofers.  Boofers sub woofer thicc I am bekom fat thicc length boy doggorino, wow very biscit wow such tempt super chub porgo. Adorable doggo super chub doing me a frighten super chub very good spot doggorino boof wrinkler, the neighborhood pupper very good spot pats doggo big ol pupper. Heckin angery woofer you are doing me the shock doge, long woofer."
    },
    "samuel-l-ipsum": {
      "name": "Samuel L Ipsum",
      "content": "Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass. Well, the way they make shows is, they make one show. That show's called a pilot. Then they show that show to the people who make shows, and on the strength of that one show they decide if they're going to make more shows. Some pilots get picked and become television programs. Some don't, become nothing. She starred in one of the ones that became nothing. Now that we know who you are, I know who I am. I'm not a mistake! It all makes sense! In a comic, you know how you can tell who the arch-villain's going to be? He's the exact opposite of the hero. And most times they're friends, like you and me! I should've known way back when... You know why, David? Because of the kids. They called me Mr Glass. Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb."
    }
  }
`)
